# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a1a816a33b865f928ccc743f7bb3eb3148b1c482d8add1464fe3a923703430b7fbdc04d45322ff04abee0de8160637239604816c1f6d2f2ccb22c3d8678967b

test:
  secret_key_base: 7cbee47d5091a50053b75bb0454fde8fc5e14ec83549fe9416f0b3a2b1ee3add088078211776cab3ecc51f497a843578560eceac72fb103869d3d9aa481cb2c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
